### PR TITLE
Adding green and yellow theme colors, formatting edits for readability & consistency 

### PR DESCRIPTION
**Pull request by tkensiski**
Added a green and yellow themes
Also cleaned up some unused imports and reformatted the css a bit for better readability

Issue: https://github.com/jenkinsci/material-theme-plugin/issues/53

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Note
I think I got everything setup for these, happy to modify as needed.
The readability is subjective I understand but consistency is not so thats what I went for.
Consistency was picked based on the first occurrence where each color was on its own line, this read nice and was easier to maintain in my opinion so I used that format for everywhere else. (https://github.com/jenkinsci/material-theme-plugin/blob/master/src/main/webapp/material-theme.css#L113-L116)

We needed these colors for our instances of jenkins that we previously used afonsof/jenkins-material-theme for; which this is based off of! Colors were taken from there, secondary colors are 75% opacity of the primary color.

### CODE REVIEW

**Comment by timbrown5** [comment]
Theme picker isn't working for me locally:
Screenshot 2022-09-16 at 12 00 09
Not sure why 😕

**Comment by timbrown5** [comment]
```
diff --git a/src/main/java/io/jenkins/plugins/materialtheme/MaterialThemeRootAction.java b/src/main/java/io/jenkins/plugins/materialtheme/MaterialThemeRootAction.java
index 48e8ba6..ae9554c 100644
--- a/src/main/java/io/jenkins/plugins/materialtheme/MaterialThemeRootAction.java
+++ b/src/main/java/io/jenkins/plugins/materialtheme/MaterialThemeRootAction.java
@@ -17,6 +17,8 @@ import static io.jenkins.plugins.materialtheme.MaterialIndigoThemeManagerFactory
 import static io.jenkins.plugins.materialtheme.MaterialRedThemeManagerFactory.MATERIAL_RED_CSS;
 import static io.jenkins.plugins.materialtheme.MaterialGreyThemeManagerFactory.MATERIAL_GREY_CSS;
 import static io.jenkins.plugins.materialtheme.MaterialLightBlueThemeManagerFactory.MATERIAL_LIGHT_BLUE_CSS;
+import static io.jenkins.plugins.materialtheme.MaterialYellowThemeManagerFactory.MATERIAL_YELLOW_CSS;
+import static io.jenkins.plugins.materialtheme.MaterialGreenThemeManagerFactory.MATERIAL_GREEN_CSS;
 
 @Extension
 public class MaterialThemeRootAction implements UnprotectedRootAction {
@@ -41,7 +43,7 @@ public class MaterialThemeRootAction implements UnprotectedRootAction {
         if (cssFile.startsWith("/")) {
             cssFile = cssFile.substring(1);
         }
-        if (!Arrays.asList(BASE_CSS, MATERIAL_INDIGO_CSS, MATERIAL_RED_CSS, MATERIAL_GREY_CSS, MATERIAL_LIGHT_BLUE_CSS, CUSTOMISED_CSS)
+        if (!Arrays.asList(BASE_CSS, MATERIAL_INDIGO_CSS, MATERIAL_RED_CSS, MATERIAL_GREY_CSS, MATERIAL_LIGHT_BLUE_CSS, MATERIAL_YELLOW_CSS, MATERIAL_GREEN_CSS, CUSTOMISED_CSS)
                 .contains(cssFile)) {
             rsp.sendError(404);
             return;
```

I think you need to add your CSS files to the root action as above.

**Review by timbrown5 — CHANGES_REQUESTED** [review]
I think you need to add the new CSS items to the root action, see:
https://github.com/jenkinsci/material-theme-plugin/pull/52#issuecomment-1249312890

**Comment by tkensiski** [comment]
> I think you need to add the new CSS items to the root action, see: [#52 (comment)](https://github.com/jenkinsci/material-theme-plugin/pull/52#issuecomment-1249312890)

Woops sorry about that, I think that should do it

Heres a screenshot too!
Screen Shot 2022-09-20 at 5 19 54 PM

**Review by timbrown5 — APPROVED** [review]

**Comment by tkensiski** [comment]
@timbrown5 looks like something went wrong in the release process and its not available to the jenkins plugin manager even tho github is showing the correct release version.

**Comment by timbrown5** [comment]
I think a build is available, but it's got the wrong version number
0.5.2-rc100.

**Pull request merged**
