### PR TITLE
Add grey and light blue theme

### PR DESCRIPTION
**Pull request by jonesbusy**
This PR add grey and light blue theme (CF screenshots)

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by timbrown5** [comment]
I think this will conflict with https://github.com/jenkinsci/material-theme-plugin/pull/11 (as @timja has refactored the existing classes to support upstream changes).
Do you require an older version of Jenkins? If I merge #11 first, then this will only be available for 2.336+.

**Comment by jonesbusy** [comment]
Hi! I'm running the current LTS (3.332.1) but if it's too complicated for merge conflicts, I can wait few month for next LTS baseline.

Regard,

**Comment by timbrown5** [comment]
#11 has been merged. You will need to refactor your to work with it (hopefully reducing the amount of code required).

**Comment by jonesbusy** [comment]
@timbrown5 Thanks! Sure I will refactor this PR.

**Pull request closed without merging**
